#%RAML 1.0 DataType
type:
    properties:
     ingredientId: 
      type: string
      minLength: 4
      maxLength: 5
     name: 
      type: string
      maxLength: 30
     quantity: number              
     unit: string
     lastUpdated: datetime-only
     