#%RAML 1.0 Trait
responses:
      201:
        body:
          example:
             message: "Ingredients created successfully."
      400:
        body:
          example:
            message: "Bad request"
      500:
        body:
          example:
            message: "Internal Server Error"