#%RAML 1.0 Trait
responses:
    200:
       body:
        example:
           message: "Ingredient updated successfully."
    404:
      body:
        example:
          message: "Ingredient not found" 
    500:
      body:
        example:
          message: "Internal server error"
            